export enum AppRoute {
  AUTH = "AUTH",
  LOGIN = "LOGIN",
  REGISTER = "REGISTER",
  FORGET_PASS = "FORGET_PASS",
  MAIN = "MAIN",
  MAIN_TAB = "MAIN_TAB",
  HOME = "HOME",
  APPOINTMENT_LIST = "APPOINTMENT_LIST",
  QUESTION_LIST = "QUESTION_LIST",
  PROFILE = "PROFILE",
}
